/**
 * 사이퍼(캐릭터) 프로필 — 능력치·스킬.
 * Neople 오픈 API 는 이 데이터를 제공하지 않으므로 공식 사이트(cyphers.nexon.com)
 * 기준 정적 데이터로 관리한다. key = characterName(한글).
 * 데이터가 있는 캐릭터만 상세 페이지에 능력치·스킬 UI 가 렌더된다.
 */

export interface CypherStat {
  attack: number; // 공격
  vitality: number; // 체력
  evasion: number; // 회피
  critical: number; // 치명
  defense: number; // 방어
  movement: number; // 이동
}

export interface CypherSkillInfo {
  slot: string; // LMB / RMB / Q / E / F / Space / Shift+LMB / Wheel Up / Passive ...
  name: string;
  cooldown?: string; // "16.50초"
  cost?: string;
  explain: string;
}

export interface CypherProfile {
  slug: string; // cyphers.nexon.com 영문 슬러그
  attackType?: string; // 원거리 / 근거리
  difficulty?: number; // 1~5 (★ 개수)
  roleDesc?: string; // 한 줄 소개
  stat?: CypherStat;
  skills?: CypherSkillInfo[];
}

/** 능력치 표시 설정 — 라벨 + 바 정규화용 대략 최대값 + 색 */
export const STAT_DISPLAY: { key: keyof CypherStat; label: string; max: number; color: string }[] = [
  { key: "attack", label: "공격", max: 130, color: "#e2506a" },
  { key: "vitality", label: "체력", max: 2100, color: "#4fbf6b" },
  { key: "defense", label: "방어", max: 35, color: "#5b8def" },
  { key: "critical", label: "치명", max: 110, color: "#e3b23c" },
  { key: "evasion", label: "회피", max: 110, color: "#a15bf0" },
  { key: "movement", label: "이동", max: 345, color: "#4f8ff0" },
];

export const PROFILES: Record<string, CypherProfile> = {
  "멜빈": {"slug": "melvin", "attackType": "원거리", "difficulty": 1, "roleDesc": "기계를 이용한 전투로 라인전에 유리한 원거리 캐릭터", "stat": {"attack": 97, "vitality": 1450, "evasion": 55, "critical": 52, "defense": 11.75, "movement": 308}, "skills": [{"slot": "LMB", "name": "부트 업", "cooldown": "0.40초", "explain": "제피 R의 오른팔 점화 장치로 세 발의 미사일을 발사합니다."}, {"slot": "RMB", "name": "EMP 쇼크", "cooldown": "7.50초", "explain": "제피 R을 발사해 이동 경로에 네 개의 역장을 순차적으로 생성합니다."}, {"slot": "Q", "name": "바이퍼", "cooldown": "16.50초", "explain": "전방에 포탑을 설치합니다. 15초간 유지되며 일정 피해를 받으면 파괴됩니다."}, {"slot": "E", "name": "그라운드 제로", "cooldown": "105.00초", "explain": "제피 L이 스크린을 전개하고 폭격을 준비합니다. E를 유지하면 방향키로 목표 지점을 지정할 수 있습니다."}, {"slot": "F", "name": "작동 오류", "cooldown": "5.00초", "explain": "두 제피가 멜빈 주변의 위협적인 적을 빠르게 공격합니다."}, {"slot": "Space", "name": "듀얼 부팅", "cooldown": "1.50초", "explain": "제피 L을 내비게이션 모드(후방 시야 +70)와 배틀 플러그인 모드(부트 업 강화)로 전환합니다."}, {"slot": "Shift+LMB", "name": "소닉 부스터", "cooldown": "5.50초", "explain": "570 거리를 고속으로 대시합니다. 적에게 피해를 주면 뒤로 돌아옵니다."}, {"slot": "Passive", "name": "순간 가속", "explain": "방향키를 두 번 눌러 잠시 이동 속도가 증가한 뒤 3초간 이동 속도가 40% 감소합니다."}]},
  "제키엘": {"slug": "jekiel", "attackType": "근거리", "difficulty": 3, "roleDesc": "강화인간 사도 제키엘", "stat": {"attack": 107, "vitality": 2070, "evasion": 56.5, "critical": 50, "defense": 16.75, "movement": 320}, "skills": [{"slot": "LMB", "name": "정화", "cooldown": "0.20초", "explain": "주먹을 테라듀로 감싸 최대 2회 공격, 두 번째 타격 시 다운"}, {"slot": "RMB", "name": "단죄", "cooldown": "10.35초", "explain": "전진해 적을 테라듀로 감싸 바닥에 여러 번 내팽개치는 잡기"}, {"slot": "E", "name": "묵시록", "cooldown": "107.00초", "explain": "높이 점프 후 테라듀로 감싸 강하 공격하며 회전으로 압박"}, {"slot": "E", "name": "구마의 손길", "cooldown": "108.00초", "explain": "테라듀를 집약한 거대한 손아귀를 발사해 적을 끌어와 타격"}, {"slot": "F", "name": "고해성사", "cooldown": "5.00초", "explain": "적을 잡아 무릎 꿇게 하고 징벌하는 잡기 스킬"}, {"slot": "Space", "name": "참회의 기도", "cooldown": "19.00초", "explain": "다운 상태에서만 사용, 원거리 공격을 방어하고 적을 밀어냄"}, {"slot": "Shift+LMB", "name": "참혹한 인도", "cooldown": "5.70초", "explain": "테라듀로 지면을 긁으며 전진, 다운된 적 포착 시 잡기"}, {"slot": "LMB+RMB", "name": "사도 강림", "cooldown": "13.00초", "explain": "테라듀 줄기를 날개처럼 펼쳐 심판 후 회수하며 징벌"}, {"slot": "Wheel Up", "name": "집행자", "explain": "90초간 방어력 +3% 증가 버프"}]},
  "레이튼": {"slug": "lleyton", "attackType": "근거리", "difficulty": 3, "roleDesc": "전기 능력자 방출의 레이튼", "stat": {"attack": 111, "vitality": 2050, "evasion": 57, "critical": 50, "defense": 14.75, "movement": 315}, "skills": [{"slot": "LMB", "name": "쓰릴 슬랩", "cooldown": "0.20초", "explain": "팔에 전류를 흘려 빠르게 최대 4회 공격, 마지막 타격에 다운"}, {"slot": "RMB", "name": "썬더클랩", "cooldown": "9.00초", "explain": "전진하며 양손에 강한 전기를 담아 공격"}, {"slot": "E", "name": "일렉버스트", "cooldown": "115.00초", "explain": "17초간 공격 속도 +10%, 모든 스킬 강화 상태 부여"}, {"slot": "E", "name": "라이트닝 브레이크", "cooldown": "105.00초", "explain": "직선으로 돌진해 적을 붙잡고 전류 방출 후 강한 대미지"}, {"slot": "F", "name": "펄스 그랩", "cooldown": "5.00초", "explain": "적을 잡은 후 몸속으로 강한 전기를 흘려보냄"}, {"slot": "Space", "name": "라이트닝 스텝", "cooldown": "8.50초", "explain": "몸을 전기로 자극해 빠르게 두 번 이동"}, {"slot": "Shift+LMB", "name": "라이트닝 볼트", "cooldown": "4.00초", "explain": "지정한 위치에 푸른 번개를 내리꽂는 원거리 공격"}, {"slot": "LMB+RMB", "name": "전자기 방출", "cooldown": "12.00초", "explain": "자신을 중심으로 강한 전자기를 모아 방출"}, {"slot": "LMB+RMB", "name": "스턴 건", "cooldown": "11.50초", "explain": "적을 붙잡아 강력한 전기를 방출(회전 가능)"}, {"slot": "Wheel Up", "name": "더스팅", "explain": "90초간 공격력 +5, 방어력 +2% 증가"}]},
  "휴톤": {"slug": "huton", "attackType": "근거리", "difficulty": 1, "roleDesc": "주먹 능력자 파괴왕 휴톤", "stat": {"attack": 106, "vitality": 2150, "evasion": 53, "critical": 45, "defense": 15.5, "movement": 320}, "skills": [{"slot": "LMB", "name": "아이리쉬 복싱", "cooldown": "0.20초", "explain": "최대 3회 공격, 세 번째 타격에 다운"}, {"slot": "RMB", "name": "바야바", "cooldown": "13.50초", "explain": "전방으로 육중하게 몸통을 날려 공격"}, {"slot": "E", "name": "핵펀치", "cooldown": "80.00초", "explain": "힘을 모아 강력한 펀치, 슈퍼 아머 상태라도 다운"}, {"slot": "E", "name": "데토네이션", "cooldown": "103.00초", "explain": "주먹을 부딪힌 뒤 강타하고 마지막 타격으로 멀리 날림"}, {"slot": "F", "name": "짐짝 던지기", "cooldown": "5.00초", "explain": "적을 잡은 후 지정한 위치로 던짐"}, {"slot": "Space", "name": "안면 가드", "cooldown": "14.50초", "explain": "제자리에서 가드 자세로 적의 강력한 공격에 대비"}, {"slot": "Shift+LMB", "name": "지옥구멍", "cooldown": "4.00초", "explain": "전방으로 점프 후 주먹으로 땅을 강하게 내려찍음"}, {"slot": "LMB+RMB", "name": "서든 어퍼", "cooldown": "8.00초", "explain": "전방으로 이동하며 어퍼컷"}, {"slot": "Wheel Up", "name": "본 스트레칭", "explain": "90초간 방어력 +3% 증가"}]},
  "디아나": {"slug": "diana", "attackType": "근거리", "difficulty": 1, "roleDesc": "자력 능력자 성흔의 디아나", "stat": {"attack": 112, "vitality": 2070, "evasion": 54.5, "critical": 50, "defense": 17.75, "movement": 325}, "skills": [{"slot": "LMB", "name": "고귀한 낙인", "cooldown": "0.20초", "explain": "자력으로 칼날 조각을 움직여 최대 2회 공격, 두 번째 타격에 다운"}, {"slot": "RMB", "name": "히든 케이지", "cooldown": "13.00초", "explain": "칼날을 날려 적을 속박하고 3초간 회피 감소"}, {"slot": "RMB", "name": "질책의 사슬", "cooldown": "12.50초", "explain": "칼날을 땅에 박아 추가 입력으로 솟아오르게 해 타격"}, {"slot": "E", "name": "네메시스", "cooldown": "100.00초", "explain": "정면으로 칼날을 날려 적들을 차례로 속박하고 끌어당겨 충돌"}, {"slot": "E", "name": "그레이스풀 프리즌", "cooldown": "103.00초", "explain": "바닥에 칼날을 일으켜 속박하고 연속 공격, 시전 중 무적"}, {"slot": "F", "name": "아라베스크", "cooldown": "5.00초", "explain": "적을 잡은 후 칼날로 궤적을 그리며 위압"}, {"slot": "Space", "name": "마그넷 체인", "cooldown": "8.00초", "explain": "칼날을 날린 후 그 위치로 자신을 끌어당김"}, {"slot": "Space", "name": "제재의 인력", "cooldown": "14.00초", "explain": "칼날을 전방으로 뻗어 적 타격 시 그 위치로 이동하며 타격"}, {"slot": "Shift+LMB", "name": "처벌의 채찍", "cooldown": "4.50초", "explain": "칼날 조각을 채찍처럼 연결해 강하게 내려침"}, {"slot": "LMB+RMB", "name": "파편의 회오리", "cooldown": "10.50초", "explain": "주변으로 칼날을 회전시켜 적을 베며 이동"}, {"slot": "LMB+RMB", "name": "체인 오브 턴", "cooldown": "12.00초", "explain": "전진하며 원형으로 채찍을 휘둘러 공격"}, {"slot": "Wheel Up", "name": "하이 클래스", "explain": "90초간 회피율 +5% 증가"}]},
  "라이언": {"slug": "ryan", "attackType": "근거리", "difficulty": 2, "roleDesc": "대지 능력자 대지의 라이언", "stat": {"attack": 109, "vitality": 2000, "evasion": 56, "critical": 48, "defense": 15.75, "movement": 320}, "skills": [{"slot": "LMB", "name": "헤드벗 해머", "cooldown": "0.20초", "explain": "단단한 몸을 부딪혀 최대 3회 공격, 세 번째에 다운"}, {"slot": "RMB", "name": "블로킹 러쉬", "cooldown": "8.50초", "explain": "에임 방향으로 질주하며 적을 밀쳐냄(회전으로 회피 가능)"}, {"slot": "E", "name": "라이언 터치다운", "cooldown": "105.00초", "explain": "바위를 타고 점프 후 내려찍어 지정 위치를 바위 벽으로 둘러쌈"}, {"slot": "F", "name": "카운터 스로잉", "cooldown": "5.00초", "explain": "적의 공격을 피하고 잡은 후 지정 위치로 던짐"}, {"slot": "Space", "name": "스톤폼", "cooldown": "30.00초", "explain": "12초간 방어력 증가·보호막 생성, 이동/공격 속도 감소"}, {"slot": "Shift+LMB", "name": "블리츠 태클", "cooldown": "5.00초", "explain": "전방으로 몸을 던져 적을 누름, 다운된 적에게는 구속"}, {"slot": "LMB+RMB", "name": "락 스매시", "cooldown": "10.00초", "explain": "힘을 모은 뒤 전방으로 돌진하며 강타(최대 3단계 차지)"}, {"slot": "Wheel Up", "name": "킵잇업", "explain": "90초간 방어력 +3% 증가"}]},
  "카로슈": {"slug": "carocho", "attackType": "근거리", "difficulty": 2, "roleDesc": "비능력자 카로슈", "stat": {"attack": 116, "vitality": 1650, "evasion": 52, "critical": 55, "defense": 12.75, "movement": 327}, "skills": [{"slot": "LMB", "name": "스크래퍼", "cooldown": "0.30초", "explain": "기괴한 검으로 최대 4회 공격, 네 번째 히트 시 다운"}, {"slot": "RMB", "name": "블러드 커터", "cooldown": "9.00초", "explain": "전방으로 점프하며 공격(강화 시 사정거리 증가·다운)"}, {"slot": "RMB", "name": "블러디 서프레션", "cooldown": "8.30초", "explain": "전방으로 돌진해 공격(강화 시 추가 타격 가능)"}, {"slot": "E", "name": "디스트로이어", "cooldown": "95.00초", "explain": "기계팔을 중화기로 변형해 다연발 유탄·확산탄으로 광범위 공격"}, {"slot": "E", "name": "엑스큐셔너", "cooldown": "97.00초", "explain": "기계팔 파일 드라이버로 돌진해 적을 붙잡고 잔혹하게 공격"}, {"slot": "F", "name": "사형집행", "cooldown": "5.00초", "explain": "적을 잡은 후 잔혹하게 베어넘김"}, {"slot": "Space", "name": "회피 기동", "cooldown": "20.00초", "explain": "위기 시 재빠르게 굴러 위기를 모면"}, {"slot": "Shift+LMB", "name": "M58 체인건", "cooldown": "4.00초", "explain": "전방 이동 후 기계팔 기관총 발사"}, {"slot": "Shift+LMB", "name": "P37 파일드라이버", "cooldown": "7.00초", "explain": "파일 드라이버로 지반을 폭발시켜 적을 타격"}, {"slot": "LMB+RMB", "name": "벙커버스터", "cooldown": "10.50초", "explain": "돌진 후 파일 드라이버로 타격(강화 시 추가 타격)"}, {"slot": "LMB+RMB", "name": "트윈 배럴", "cooldown": "9.00초", "explain": "기계팔 샷건으로 적을 날려버림(강화 시 최대 2발)"}, {"slot": "Wheel Up", "name": "칠링", "explain": "90초간 치명타 +5% 증가"}, {"slot": "Passive", "name": "악의 경계선", "explain": "전투로 얻은 점수에 따라 일부 스킬이 강화되는 패시브"}]},
  "브루스": {"slug": "bruce", "attackType": "근거리", "difficulty": 3, "roleDesc": "전방에서 적의 공격을 버티며 진영을 붕괴시키기에 적합한 스킬을 많이 보유하고 있습니다.", "stat": {"attack": 105, "vitality": 2260, "evasion": 52, "critical": 45, "defense": 15.75, "movement": 315}, "skills": [{"slot": "LMB", "name": "연어사냥", "cooldown": "0.20초", "explain": "발톱을 세워 크게 휘둘러 공격하며 최대 2회, 2타에 다운시킵니다."}, {"slot": "RMB", "name": "베어 러쉬", "cooldown": "9.00초", "explain": "정면으로 빠르게 돌진한 후 발톱을 크게 휘두릅니다. 최대 3단계 차지 가능."}, {"slot": "E", "name": "기간틱 베어", "cooldown": "120.00초", "explain": "몸을 거대화해 돌진하며 하울링·돌진 공격이 가능하고 방어력이 30% 증가합니다."}, {"slot": "F", "name": "숨통끊기", "cooldown": "5.00초", "explain": "적을 잡아 들어올린 후 바닥에 강하게 내려찍습니다."}, {"slot": "Space", "name": "야생 본능", "cooldown": "22.00초", "explain": "공중 상태에서 회복하며 저체력 시 쿨타임이 감소하고 보호막을 부여합니다."}, {"slot": "Shift+LMB", "name": "맹수의 응징", "cooldown": "4.50초", "explain": "점프한 후 야수의 힘을 실어 강하게 내려찍습니다."}, {"slot": "LMB+RMB", "name": "하울링", "cooldown": "11.00초", "explain": "정면을 향해 크게 포효하여 1.5초간 청각 장애를 유발합니다."}, {"slot": "Wheel Up", "name": "손톱갈기", "explain": "90초간 방어력이 3% 증가하는 버프입니다."}]},
  "루이스": {"slug": "louis", "attackType": "근거리", "difficulty": 2, "roleDesc": "적을 무력화시킬 수 있어 1:1에 강한 캐릭터", "stat": {"attack": 119, "vitality": 1830, "evasion": 54, "critical": 55, "defense": 14.25, "movement": 337}, "skills": [{"slot": "LMB", "name": "결정검", "cooldown": "0.20초", "explain": "결정으로 2회 연속 공격하며 2타에 다운시킵니다."}, {"slot": "RMB", "name": "샤드리볼버", "cooldown": "10.00초", "explain": "결정 파편을 발사하며 거리에 따라 최대 3회 타격합니다."}, {"slot": "E", "name": "영구동토", "cooldown": "110.00초", "explain": "주변 모든 적을 2초간 얼려버리며 강력한 피해를 줍니다."}, {"slot": "F", "name": "감람석 망치", "cooldown": "5.00초", "explain": "적을 잡아 결정 망치로 내려쳐 다운시킵니다."}, {"slot": "Space", "name": "결정 슬라이드", "cooldown": "20.00초", "explain": "목표 지점까지 결정 레일을 만들어 경로의 적에게 피해를 줍니다."}, {"slot": "Shift+LMB", "name": "아이스버그", "cooldown": "4.00초", "explain": "지정 위치에 얼음 가시를 소환해 다운시킵니다."}, {"slot": "LMB+RMB", "name": "드라이아이스", "cooldown": "8.00초", "explain": "가는 결정을 쏘아 1초간 빙결시킵니다."}, {"slot": "Wheel Up", "name": "디프로스트", "explain": "90초간 공격력이 10 증가하는 버프입니다."}]},
  "도일": {"slug": "doyle", "attackType": "근거리", "difficulty": 1, "roleDesc": "적의 공격을 버티는 다양한 슈퍼아머 스킬", "stat": {"attack": 107, "vitality": 2170, "evasion": 54.5, "critical": 45, "defense": 17, "movement": 320}, "skills": [{"slot": "LMB", "name": "캐논 복싱", "cooldown": "0.20초", "explain": "두터운 주먹을 묵직하게 휘둘러 공격하며 최대 3회, 3타에 다운시킵니다."}, {"slot": "RMB", "name": "더블 래리어트", "cooldown": "11.00초", "explain": "두 팔을 펼쳐 빙글빙글 돌며 주변 적을 공격합니다. 슈퍼아머·방어력 증가·보호막 생성."}, {"slot": "E", "name": "초 스트레이트", "cooldown": "75.00초", "explain": "주먹에 힘을 모아 강력한 펀치를 날립니다. 슈퍼아머·보호막·잡기면역."}, {"slot": "E", "name": "크럼블링 가이아", "cooldown": "110.00초", "explain": "강력한 진동으로 대지진을 일으켜 적을 공격하며 우클릭으로 즉시 마무리할 수 있습니다."}, {"slot": "F", "name": "짐짝 던지기", "cooldown": "5.00초", "explain": "적을 잡은 후 바닥에 내동댕이칩니다."}, {"slot": "Space", "name": "근육 다지기", "cooldown": "33.00초", "explain": "근육을 다져 방어력이 증가하나 공격력과 이동속도가 감소합니다."}, {"slot": "Shift+LMB", "name": "지옥구멍", "cooldown": "4.50초", "explain": "전방으로 점프한 뒤 주먹으로 땅을 강하게 내려찍습니다."}, {"slot": "LMB+RMB", "name": "캐논 어퍼", "cooldown": "8.00초", "explain": "전방으로 이동하며 어퍼컷을 날립니다. 슈퍼아머."}, {"slot": "Wheel Up", "name": "본 스트레칭", "explain": "90초간 방어력이 3% 증가하는 버프입니다."}, {"slot": "Passive", "name": "작업 반장", "explain": "회복력이 5% 증가합니다."}]},
  "루카": {"slug": "luka", "attackType": "근거리", "difficulty": 3, "roleDesc": "제어 불가의 중독 능력으로 자신의 체력을 소모시키는 대신 강력한 버프", "stat": {"attack": 105, "vitality": 1570, "evasion": 56, "critical": 55, "defense": 14.5, "movement": 328}, "skills": [{"slot": "LMB", "name": "독아베기", "cooldown": "0.25초", "explain": "세 번 공격하며 3타에 다운 및 중독 상태를 부여합니다."}, {"slot": "RMB", "name": "파독검", "cooldown": "9.20초", "explain": "전방 이동 후 찌르며 독의 힘 해방 시 15초간 강화되나 지속 피해가 발생합니다."}, {"slot": "RMB", "name": "섬독", "cooldown": "9.35초", "explain": "전방으로 빠르게 이동하며 적을 찔러 중독 상태를 부여합니다(해방 상태)."}, {"slot": "Q", "name": "강제해방", "cooldown": "25.00초", "explain": "독의 힘을 강제 해방해 15초간 강화하고 주변 적에게 독기 피해를 줍니다."}, {"slot": "E", "name": "사혈독류파", "cooldown": "109.30초", "explain": "독의 힘을 극한까지 끌어내 거대한 검기를 날립니다."}, {"slot": "E", "name": "검은 전이", "cooldown": "100.00초", "explain": "독 폭주로 전방 모든 적을 공격하며 정면 방어력 20%를 획득합니다(해방 상태)."}, {"slot": "F", "name": "흑로 내려베기", "cooldown": "5.80초", "explain": "적을 잡아 벤 후 회피하며 독의 검기를 방출합니다."}, {"slot": "Space", "name": "승천베기", "cooldown": "12.70초", "explain": "빠르게 올려 베며 연계가 가능하고 해방 시 잡기로 변경됩니다."}, {"slot": "Shift+LMB", "name": "갈대가르기", "cooldown": "6.50초", "explain": "독의 검기를 전방으로 날려 중독 상태를 부여합니다."}, {"slot": "LMB+RMB", "name": "흉월베기", "cooldown": "12.70초", "explain": "연속으로 검을 휘두르며 우클릭 연계 시 올려베기, 해방 시 추가 검기가 발생합니다."}, {"slot": "LMB+RMB", "name": "삭월베기", "cooldown": "10.50초", "explain": "전진 후 회전하며 내려베고 해방 시 이동거리가 증가합니다."}, {"slot": "Wheel Up", "name": "호접몽", "explain": "90초간 치명타가 5% 증가하는 버프입니다."}]},
  "벨져": {"slug": "belzer", "attackType": "근거리", "difficulty": 3, "roleDesc": "빠른 속도로 적과의 거리를 좁히는 스킬 보유", "stat": {"attack": 105, "vitality": 1900, "evasion": 59.5, "critical": 55, "defense": 14.5, "movement": 325}, "skills": [{"slot": "LMB", "name": "쾌속 베기", "cooldown": "0.20초", "explain": "두 검으로 최대 3회 공격하며 3타에 다운시킵니다."}, {"slot": "RMB", "name": "섬광궤적", "cooldown": "10.00초", "explain": "검을 던진 후 빠르게 이동해 회수하며 베어냅니다."}, {"slot": "E", "name": "백야천영섬", "cooldown": "95.00초", "explain": "강한 검기로 적을 띄운 후 섬광처럼 이동하며 모두 베어냅니다."}, {"slot": "E", "name": "만경창파", "cooldown": "85.00초", "explain": "힘을 모아 섬광처럼 이동하며 전방의 모든 적을 베어냅니다."}, {"slot": "F", "name": "일도", "cooldown": "5.00초", "explain": "적을 잡은 후 순식간에 베어냅니다."}, {"slot": "Space", "name": "귀안도", "cooldown": "25.00초", "explain": "다운 상태에서 사용해 원거리 공격을 튕겨내 반격합니다."}, {"slot": "Space", "name": "섬격", "cooldown": "10.00초", "explain": "빠르게 이동하며 적을 교차로 베어냅니다."}, {"slot": "Shift+LMB", "name": "그믐달 베기", "cooldown": "4.35초", "explain": "정면으로 휘젓듯 이동한 뒤 적을 베어냅니다."}, {"slot": "LMB+RMB", "name": "격류 베기", "cooldown": "13.50초", "explain": "이동 후 올려 베기와 연계 공격을 합니다."}, {"slot": "LMB+RMB", "name": "소월 베기", "cooldown": "10.00초", "explain": "올려 베며 사라진 뒤 나타나 사선으로 연속 베기합니다."}, {"slot": "Wheel Up", "name": "호접의", "explain": "90초간 치명타가 5% 증가하는 버프입니다."}]},
  "아이작": {"slug": "issac", "attackType": "근거리", "difficulty": 2, "roleDesc": "다양한 잡기 스킬로 적을 제압하는 데 특화", "stat": {"attack": 106, "vitality": 2130, "evasion": 59, "critical": 50, "defense": 16.5, "movement": 325}, "skills": [{"slot": "LMB", "name": "엘리게이터", "cooldown": "0.20초", "explain": "강화된 악력으로 묵직하게 내려치며 최대 3회, 3타에 다운시킵니다."}, {"slot": "RMB", "name": "레이지 런", "cooldown": "9.00초", "explain": "정면으로 매섭게 돌진하며 적을 튕겨내고 다운된 적은 밟고 지나갑니다."}, {"slot": "E", "name": "터미네이트 스윙", "cooldown": "110.00초", "explain": "적의 다리를 잡은 채 빙글빙글 돌린 후 멀리 던져버립니다."}, {"slot": "E", "name": "멜러볼런스", "cooldown": "113.00초", "explain": "신체를 과열시켜 강화 상태에 진입하며 우클릭·양클릭 스킬이 변경됩니다."}, {"slot": "F", "name": "헤드 크래쉬", "cooldown": "5.00초", "explain": "적을 잡은 후 뒤로 메다 꽂습니다."}, {"slot": "Space", "name": "롤링 닷지", "cooldown": "19.00초", "explain": "다운 시 사용해 빠르게 구르며 일어나 모든 공격을 피합니다."}, {"slot": "Shift+LMB", "name": "저지먼트 엘보", "cooldown": "5.35초", "explain": "점프하여 팔꿈치로 지면을 강하게 내려찍은 후 옆구르기로 일어납니다."}, {"slot": "LMB+RMB", "name": "데드맨 크라우칭", "cooldown": "13.50초", "explain": "전진하여 적의 목을 잡아 올린 뒤 방패막이로 사용합니다."}, {"slot": "Wheel Up", "name": "세레모니", "explain": "90초간 공격력과 방어력이 증가하는 버프입니다."}]},
  "트리비아": {"slug": "trivia", "attackType": "원거리", "difficulty": 3, "roleDesc": "다양한 회피기와 긴 사정거리의 스킬 보유", "stat": {"attack": 86, "vitality": 1350, "evasion": 52, "critical": 57, "defense": 10, "movement": 305}, "skills": [{"slot": "Passive", "name": "흡혈", "explain": "자신이 입힌 피해의 5%만큼 체력을 회복합니다."}, {"slot": "LMB", "name": "박쥐", "cooldown": "0.45초", "explain": "그림자 박쥐를 만들어 전방으로 날립니다. 이동 중에도 사용 가능합니다."}, {"slot": "RMB", "name": "부츠커터", "cooldown": "7.50초", "explain": "칼날을 부메랑처럼 날려 공격하며 출혈 상태를 유발합니다."}, {"slot": "E", "name": "비행", "cooldown": "103.00초", "explain": "자유롭게 하늘을 날아다니며 박쥐 공격과 강하 공격이 가능합니다."}, {"slot": "F", "name": "데스글라이드", "cooldown": "5.00초", "explain": "적의 머리를 잡고 날아오른 후 땅에 내리꽂아 던져버립니다."}, {"slot": "Space", "name": "변이", "cooldown": "25.00초", "explain": "박쥐 떼로 변해 이동하며 모든 공격을 회피합니다."}, {"slot": "Shift+LMB", "name": "킬힐", "cooldown": "8.00초", "explain": "지정 위치로 순간이동한 뒤 밟기 공격으로 출혈을 유발합니다."}, {"slot": "LMB+RMB", "name": "박쥐폭풍", "cooldown": "9.50초", "explain": "지정한 위치로 여러 마리의 그림자 박쥐를 날려 공격합니다."}, {"slot": "Wheel Up", "name": "안나수이", "explain": "90초간 흡혈률을 5% 증가시키는 버프 스킬입니다."}]},
  "레베카": {"slug": "rebecca", "attackType": "근거리", "difficulty": 3, "roleDesc": "적의 공격을 피하고 근접 공격을 반격하는 스킬", "stat": {"attack": 106, "vitality": 2080, "evasion": 57.75, "critical": 50, "defense": 16.25, "movement": 325}, "skills": [{"slot": "LMB", "name": "스닉 펀치", "cooldown": "0.25초", "explain": "테라듀로 강화된 주먹으로 최대 3회 공격하며 3번째 타격이 적을 다운시킵니다."}, {"slot": "RMB", "name": "테라듀 러쉬", "cooldown": "9.00초", "explain": "빠르게 전진하며 연타로 공격하고 피격 시 0.9초 기절을 유발하며 더킹이 강화됩니다."}, {"slot": "RMB", "name": "플리커", "cooldown": "9.00초", "explain": "재빠른 잽을 날려 적을 끌어오며 공격하고 피격 시 더킹이 강화됩니다."}, {"slot": "E", "name": "케이스 오버", "cooldown": "80.00초", "explain": "강화된 펀치를 준비하며 근거리 공격을 받으면 카운터로 반격해 공격력과 범위가 증가합니다."}, {"slot": "E", "name": "디스아머먼트", "cooldown": "84.00초", "explain": "돌진하여 대상을 붙잡아 던지고 잡힌 적의 방어력을 10초간 14% 감소시킵니다."}, {"slot": "F", "name": "레이지 블로", "cooldown": "5.00초", "explain": "잡은 적을 테라듀 주먹으로 최대 5회 강타한 뒤 마무리 공격으로 종료합니다."}, {"slot": "Space", "name": "더킹", "cooldown": "8.00초", "explain": "더킹으로 파고들거나 공격을 회피하며 회피율이 18% 증가하고 좌클릭으로 어퍼컷 연계가 가능합니다."}, {"slot": "Shift+LMB", "name": "아이언 크래쉬", "cooldown": "4.00초", "explain": "전방으로 점프한 뒤 테라듀로 감싼 주먹으로 강하게 내려찍습니다."}, {"slot": "LMB+RMB", "name": "뎀프시롤", "cooldown": "9.00초", "explain": "몸을 흔들며 주먹을 휘두른 후 어퍼컷을 날리고 피격 시 더킹 강화 및 쿨타임이 초기화됩니다."}, {"slot": "Wheel Up", "name": "워밍 업", "explain": "날렵한 잽을 날리며 전투를 준비해 90초간 회피율을 5% 증가시킵니다."}]},
  "로라스": {"slug": "loras", "attackType": "근거리", "difficulty": 2, "roleDesc": "모든 상황에서 무난한 성능을 가진 기본 캐릭터", "stat": {"attack": 119, "vitality": 1800, "evasion": 54, "critical": 56, "defense": 15, "movement": 332}, "skills": [{"slot": "LMB", "name": "용창 2식", "cooldown": "0.28초", "explain": "창으로 재빠르게 두 번 찌르며 올려치는 기본 공격으로 두 번째 타격이 적을 다운시킵니다."}, {"slot": "RMB", "name": "투창 1식", "cooldown": "7.00초", "explain": "전방으로 창을 던지는 원거리 공격으로 전진 키 2회 후 사용 시 사거리가 200 증가하고 다운을 유발합니다."}, {"slot": "RMB", "name": "기사도", "cooldown": "7.50초", "explain": "전방으로 강하게 돌진하며 공격하고 검룡의 심판 또는 나선창 이후 연계가 가능합니다."}, {"slot": "E", "name": "용창 비전식 용성락", "cooldown": "115.00초", "explain": "높이 점프하여 목표 지점에 강하 공격을 하며 공중에서 시야가 5000 확장되고 적에게 표적 마크를 표시합니다."}, {"slot": "E", "name": "용창 비전식 용성진", "cooldown": "105.00초", "explain": "적에게 빠르게 접근해 연속 찌르기 후 강력한 일격으로 내려찍으며 돌진 중 무적 상태가 됩니다."}, {"slot": "F", "name": "검룡 떨어뜨리기", "cooldown": "5.00초", "explain": "적을 잡고 하늘로 뛰어올라 내려찍는 잡기 기술로 잡기 판정 1레벨을 보유합니다."}, {"slot": "Space", "name": "용창 16식 기상창", "cooldown": "12.00초", "explain": "다운 상태에서만 사용 가능하며 빠르게 일어나 정면의 적을 공격합니다."}, {"slot": "Shift+LMB", "name": "검룡의 심판", "cooldown": "4.00초", "explain": "전진하며 창으로 바닥을 강하게 내려찍는 기본 공격 변형 기술입니다."}, {"slot": "LMB+RMB", "name": "용창 22식 나선창", "cooldown": "9.00초", "explain": "몸을 길게 뻗으며 전방으로 강력한 찌르기 3연타를 수행합니다."}, {"slot": "Wheel Up", "name": "용창 17식 예의표하기", "explain": "90초간 공격력 +5, 방어력 +2%를 증가시키는 버프 기술입니다."}]},
  "자네트": {"slug": "jannette", "attackType": "근거리", "difficulty": 3, "roleDesc": "빠르고 사거리가 긴 스킬, 방어력을 무시하는 방어관통", "stat": {"attack": 111, "vitality": 1700, "evasion": 57, "critical": 57, "defense": 13.5, "movement": 332}, "skills": [{"slot": "LMB", "name": "스타카토", "cooldown": "0.25초", "explain": "세검을 날카롭게 휘둘러 최대 3회 공격하며 세 번째 타격이 적을 다운시킵니다."}, {"slot": "RMB", "name": "자발레타", "cooldown": "8.00초", "explain": "전방으로 미끄러지며 Z 모양으로 베고 세 번째 타격 시 7초간 출혈을 부여합니다."}, {"slot": "E", "name": "로즈 드라이브", "cooldown": "90.00초", "explain": "전방 970 거리를 이동하며 폭풍처럼 연속으로 찌르고 벱니다."}, {"slot": "E", "name": "로젠 카발리어", "cooldown": "100.00초", "explain": "400 범위 내 모든 적을 타격하며 첫 타격이 슈퍼아머를 파괴하고 관통 타격으로 다운을 유발합니다."}, {"slot": "F", "name": "폴링 블로썸", "cooldown": "5.00초", "explain": "적을 잡은 후 신속하게 3단계 베기 공격을 수행합니다."}, {"slot": "Space", "name": "팬텀스텝", "cooldown": "15.00초", "explain": "후방으로 390 거리를 빠르게 이동하고 추가 조작으로 전방 대시 공격이 가능합니다."}, {"slot": "Shift+LMB", "name": "플로라", "cooldown": "4.65초", "explain": "지정한 위치에 630 사거리의 검풍을 날려 적을 공격합니다."}, {"slot": "LMB+RMB", "name": "프레스토", "cooldown": "10.00초", "explain": "전방 590 거리를 이동하며 날렵한 찌르기로 연속 공격합니다."}, {"slot": "Wheel Up", "name": "샬뤼", "explain": "90초간 치명타를 5% 증가시키는 버프를 제공합니다."}, {"slot": "Passive", "name": "관통", "explain": "모든 스킬이 적의 방어구를 뚫으며 피격된 적의 방어력을 감소시킵니다."}]},
  "호타루": {"slug": "hotaru", "attackType": "근거리", "difficulty": 3, "roleDesc": "적에게 혼란을 주는 스킬과 빠르고 경쾌한 공격", "stat": {"attack": 111, "vitality": 1610, "evasion": 58, "critical": 58, "defense": 11.5, "movement": 332}, "skills": [{"slot": "LMB", "name": "제비 날리기", "cooldown": "0.45초", "explain": "전방으로 표창을 빠르게 세 번 연속 던지며 이동 중에도 사용 가능합니다."}, {"slot": "RMB", "name": "인술-폭연", "cooldown": "9.00초", "explain": "전방으로 이동하며 적 몸에 폭탄을 부착하고 인술-둔갑과 쿨타임을 공유합니다."}, {"slot": "Q", "name": "인술-둔갑", "cooldown": "9.00초", "explain": "세 가지 형태 중 하나로 변신하여 다양한 효과를 얻습니다."}, {"slot": "E", "name": "환영분신", "cooldown": "105.00초", "explain": "기폭찰을 던지고 분신을 소환해 적을 공격하며 분신은 18초간 지속됩니다."}, {"slot": "E", "name": "진화타겁", "cooldown": "88.00초", "explain": "돌진하여 표식을 남기고 E키 재입력으로 수리검 공격이 가능하며 적을 공중에 띄웁니다."}, {"slot": "F", "name": "귀신잡기", "cooldown": "5.00초", "explain": "적을 잡은 후 앞으로 던져버립니다."}, {"slot": "Space", "name": "나락 밟기", "cooldown": "15.00초", "explain": "허공을 밟고 연속 점프하며 점프 중 다른 기술 연계가 가능합니다."}, {"slot": "Shift+LMB", "name": "그림자 쐐기", "cooldown": "6.00초", "explain": "지정 위치에 쐐기를 발생시켜 적을 속박하고 이동·공격 속도를 감소시킵니다."}, {"slot": "LMB+RMB", "name": "비연폭", "cooldown": "10.00초", "explain": "여러 개의 폭탄 구슬을 던지며 나락 밟기와 연계 시 폭탄이 넓게 퍼집니다."}, {"slot": "Wheel Up", "name": "수리검장착", "explain": "90초간 추가 공격력을 10 증가시키는 버프 효과입니다."}]},
  "앨리셔": {"slug": "alicia", "attackType": "원거리", "difficulty": 2, "roleDesc": "아군 강화와 지원에 특화된 원거리 캐릭터", "stat": {"attack": 87, "vitality": 1600, "evasion": 54.5, "critical": 50, "defense": 11.5, "movement": 305}, "skills": [{"slot": "LMB", "name": "충격의 빛", "cooldown": "0.47초", "explain": "손에 빛을 모아 원거리 적을 공격하며 충전 후 발동 시 다운 효과를 부여합니다."}, {"slot": "RMB", "name": "축복의 빛", "cooldown": "7.00초", "explain": "빛의 구체를 자신이나 아군에게 발사해 공격력·방어력·이동속도를 35초간 증가시킵니다."}, {"slot": "E", "name": "심판의 빛", "cooldown": "85.00초", "explain": "공중으로 뛰어올라 빛을 모은 뒤 방출하며 최대 3단계 충전이 가능하고 원거리 방어력을 증가시킵니다."}, {"slot": "E", "name": "빛의 아리아", "cooldown": "105.00초", "explain": "공중으로 떠올라 빛을 모아 아군에게 전달하며 광범위 버프와 회복 오라를 생성합니다."}, {"slot": "F", "name": "프랑켄 슈타이너", "cooldown": "5.00초", "explain": "다리로 적을 휘감은 후 몸을 뒤집어 바닥에 내동댕이치는 잡기 기술입니다."}, {"slot": "Space", "name": "블링크", "cooldown": "30.00초", "explain": "피해를 입었을 때만 사용 가능하며 즉시 순간이동하여 위기를 모면합니다."}, {"slot": "Shift+LMB", "name": "엔젤프레스", "cooldown": "4.00초", "explain": "지정 위치로 점프해 무릎으로 찍은 후 되돌아오는 이동 공격입니다."}, {"slot": "LMB+RMB", "name": "광자력빔", "cooldown": "10.00초", "explain": "눈에서 광선을 발사하여 원거리 적을 공격합니다."}, {"slot": "Wheel Up", "name": "응원의 키스", "explain": "자신과 주변 아군의 방어력을 90초간 2% 증가시키는 버프 스킬입니다."}]},
  "티모시": {"slug": "timothy", "attackType": "근거리", "difficulty": 2, "roleDesc": "적을 묶어두거나 공격을 차단하는 능력. 폭주했을 때 높은 피해", "stat": {"attack": 106, "vitality": 2080, "evasion": 55, "critical": 46, "defense": 15.25, "movement": 320}, "skills": [{"slot": "LMB", "name": "파이어 피스트", "cooldown": "0.20초", "explain": "주먹에서 불을 방출해 최대 3회 연속 공격, 3타에 다운"}, {"slot": "RMB", "name": "잿불의 성채", "cooldown": "9.50초", "explain": "돌진 후 원거리 공격을 막는 불의 벽 생성, 화상 부여"}, {"slot": "E", "name": "슈퍼 노바", "cooldown": "95.00초", "explain": "커다란 불덩이를 전방으로 던져 원거리 방어력 증가 및 화상 부여"}, {"slot": "E", "name": "회록", "cooldown": "105.00초", "explain": "주변 적을 끌어당긴 뒤 강력한 불기둥으로 공격"}, {"slot": "F", "name": "염화 분신", "cooldown": "5.00초", "explain": "적을 잡은 후 불길로 공격하고 마지막에 불의 벽 생성"}, {"slot": "Space", "name": "정념폭발", "cooldown": "7.00초", "explain": "피격 시 주변을 공격하고 15초간 폭주 상태 진입, 방어력·스킬 강화"}, {"slot": "Shift+LMB", "name": "번 버스터", "cooldown": "6.50초", "explain": "정면으로 이동하며 불을 뿜어 공격, 반동으로 뒤로 밀림"}, {"slot": "R", "name": "화염포", "cooldown": "10.00초", "explain": "원거리로 불을 지속 방출해 공격, 이동속도 감소"}, {"slot": "Wheel Up", "name": "소등", "explain": "90초 동안 자신의 방어력 +3%"}]},
  "웨슬리": {"slug": "wesley", "attackType": "근거리", "difficulty": 2, "roleDesc": "회복 스킬과 회피기, 지형지물을 이용한 전투", "stat": {"attack": 91, "vitality": 1400, "evasion": 51.5, "critical": 55, "defense": 9, "movement": 305}, "skills": [{"slot": "LMB", "name": "데저트 스톰", "cooldown": "0.50초", "explain": "전방으로 최대 8발을 발사, 마지막 탄에 맞은 적은 다운"}, {"slot": "RMB", "name": "퍼스트 에이드킷", "cooldown": "16.00초", "explain": "구급 상자를 던져 아군 체력 회복"}, {"slot": "Q", "name": "M19 대전차지뢰", "cooldown": "9.00초", "explain": "지뢰를 설치해 적이 접근하면 폭발, 화상 유발"}, {"slot": "E", "name": "B29 지원폭격", "cooldown": "100.00초", "explain": "신호탄으로 지원 요청, 지정 위치에 폭탄 투하"}, {"slot": "E", "name": "UH-35 군수보급", "cooldown": "95.00초", "explain": "헬기로 보급품 투하, 27초간 돌격소총으로 변경되어 능력치 상승"}, {"slot": "F", "name": "즉결심판", "cooldown": "5.00초", "explain": "적을 잡은 후 탄환을 발사하는 잡기 스킬"}, {"slot": "Space", "name": "긴급회피", "cooldown": "12.00초", "explain": "재빠르게 굴러 모든 공격을 회피하는 무적 이동"}, {"slot": "Shift+LMB", "name": "M5MK2 공성류탄", "cooldown": "4.00초", "explain": "수류탄을 던져 피해를 주거나 바닥에서 폭발"}, {"slot": "Wheel Up", "name": "재장전", "explain": "탄창 교체로 자신과 주변 아군의 스킬 공격력 90초간 +2%"}]},
  "토마스": {"slug": "thomas", "attackType": "원거리", "difficulty": 2, "roleDesc": "적의 움직임을 봉쇄하는 다양한 원거리 스킬", "stat": {"attack": 79, "vitality": 1600, "evasion": 58.5, "critical": 50, "defense": 14, "movement": 305}, "skills": [{"slot": "LMB", "name": "조각의 지휘", "cooldown": "0.45초", "explain": "지정 위치에 얼음 조각을 생성해 최대 3회 공격"}, {"slot": "RMB", "name": "서릿발 감옥", "cooldown": "12초", "explain": "지정 위치 주변에 얼음 감옥을 만들어 적을 가둠"}, {"slot": "Q", "name": "크리스탈 허리케인", "cooldown": "100초", "explain": "전방을 얼려버리는 강력한 얼음 회오리 발동"}, {"slot": "E", "name": "글레이셜 피나클", "cooldown": "93.5초", "explain": "거대한 얼음 기둥으로 적을 가두고 얼려버리는 궁극기"}, {"slot": "F", "name": "감람석 망치", "cooldown": "6.5초", "explain": "적을 잡은 후 결정을 망치처럼 만들어 내려침"}, {"slot": "Space", "name": "결정슬라이드", "cooldown": "19초", "explain": "결정 레일을 만들어 빠르게 이동하며 경로의 적 공격"}, {"slot": "Shift+LMB", "name": "아이스버그", "cooldown": "5초", "explain": "지정 위치 지면에서 얼음 기둥이 솟아 공격"}, {"slot": "LMB+RMB", "name": "드라이아이스", "cooldown": "9.5초", "explain": "무수한 결정을 얇게 날려 적을 얼림"}, {"slot": "Wheel Up", "name": "디프로스트", "explain": "90초간 모든 스킬 쿨타임 -3% 가속"}]},
  "다이무스": {"slug": "deimus", "attackType": "근거리", "difficulty": 1, "roleDesc": "넓은 스킬 범위와 근접 스킬에 대한 카운터 어택", "stat": {"attack": 115, "vitality": 1760, "evasion": 56.5, "critical": 55, "defense": 14.95, "movement": 337}, "skills": [{"slot": "LMB", "name": "신속베기", "cooldown": "0.20초", "explain": "최대 3회 공격, 3타에 맞은 적은 다운"}, {"slot": "RMB", "name": "질풍베기", "cooldown": "9.00초", "explain": "전방으로 빠르게 이동하며 적을 올려 벰, 다운된 적은 더 높게 띄움"}, {"slot": "RMB", "name": "나래베기", "cooldown": "11.00초", "explain": "검풍을 날려 타격, 추가 입력 시 적 뒤로 순간 이동해 검격"}, {"slot": "E", "name": "절명참철도", "cooldown": "90.00초", "explain": "허리의 태도를 빠르게 발도해 적을 벰"}, {"slot": "E", "name": "월영즉식", "cooldown": "100.00초", "explain": "태도로 힘을 모아 적을 벰, 시전 중 전방 방어력 70% 증가"}, {"slot": "F", "name": "백로 떨어뜨리기", "cooldown": "5.00초", "explain": "적을 잡은 후 신속하게 벰"}, {"slot": "Space", "name": "심안도", "cooldown": "15.00초", "explain": "정면 근거리 공격을 무효화하고 반격, 비근거리 공격엔 반격 취소"}, {"slot": "Shift+LMB", "name": "장작쪼개기", "cooldown": "4.50초", "explain": "지정 위치에 검풍을 날려 공격"}, {"slot": "LMB+RMB", "name": "보름달베기", "cooldown": "10.00초", "explain": "힘을 모아 전진 발도, 최대 3단계 차지"}, {"slot": "Wheel Up", "name": "호접살", "explain": "90초 동안 치명타 +5%"}]},
  "레오노르": {"slug": "leonor", "attackType": "근거리", "difficulty": 2, "roleDesc": "견고한 방어 능력. 지역을 장악하고 적의 진입을 차단", "stat": {"attack": 107, "vitality": 2100, "evasion": 56, "critical": 45, "defense": 16.5, "movement": 315}, "skills": [{"slot": "LMB", "name": "용창4식", "cooldown": "0.25초", "explain": "창과 방패를 번갈아 공격, 3타에 다운"}, {"slot": "RMB", "name": "용창 21식 돌격창", "cooldown": "10초", "explain": "돌진하며 잡은 적을 창으로 찌르고, 지형 충돌 시 방패로 밀쳐 기절"}, {"slot": "E", "name": "폭룡 비전식 용격", "cooldown": "100초", "explain": "거대한 창으로 주변 적을 휩쓸어 올린 뒤 내려찍음"}, {"slot": "E", "name": "폭룡 비전식 용린", "cooldown": "120초", "explain": "강력하게 돌진 후 창을 내려찍고 주변 아군에 슈퍼아머 오라 부여"}, {"slot": "F", "name": "실렌시아", "cooldown": "5초", "explain": "창으로 적을 넘어뜨린 뒤 방패로 강하게 내려찍음"}, {"slot": "Space", "name": "철벽 태세", "cooldown": "8.5초", "explain": "방어 자세로 전방 공격 방어, 방어 게이지 소모, 방어 시 특정 스킬 쿨감"}, {"slot": "Shift+LMB", "name": "폭룡의 심판", "cooldown": "4.75초", "explain": "창을 내려쳐 대지에 균열을 일으켜 추가 피해"}, {"slot": "LMB+RMB", "name": "전술지휘-투창", "cooldown": "14.5초", "explain": "부대원들에게 투창을 대기시켜 범위 내 접근한 적 공격"}, {"slot": "Wheel Up", "name": "용창 17식 예의표하기", "explain": "자신과 주변 아군의 방어력 90초간 +2%"}]},
  "테이": {"slug": "tei", "attackType": "근거리", "difficulty": 3, "roleDesc": "뛰어난 콤보 능력으로 순식간에 적을 연속 제압", "stat": {"attack": 118, "vitality": 1700, "evasion": 55, "critical": 59, "defense": 12.6, "movement": 332}, "skills": [{"slot": "LMB", "name": "살연무", "cooldown": "0.30초", "explain": "최대 3회 공격, 3타에 맞은 적은 다운"}, {"slot": "RMB", "name": "흑풍각", "cooldown": "8.00초", "explain": "전진하며 연속 돌려차기 공격"}, {"slot": "E", "name": "암월비각", "cooldown": "100.00초", "explain": "그림자를 내보낸 후 그 위치로 이동해 강력한 내려차기"}, {"slot": "E", "name": "산영소환생", "cooldown": "110.00초", "explain": "그림자를 보내 적을 연타, 저체력 적에게 추가 연계 기회 제공"}, {"slot": "F", "name": "암습", "cooldown": "5.00초", "explain": "그림자를 박쥐 떼로 변화시켜 공격 후 기습"}, {"slot": "Space", "name": "흑영 장막", "cooldown": "10.50초", "explain": "그림자로 몸을 둘러 피해 경감, 다음 공격 강화"}, {"slot": "Shift+LMB", "name": "암영", "cooldown": "5.10초", "explain": "적의 발밑에 그림자를 보내 공격"}, {"slot": "Shift+RMB", "name": "무영격", "cooldown": "9.00초", "explain": "전방으로 빠르게 이동 후 빠른 연속 공격"}, {"slot": "Wheel Up", "name": "교서", "explain": "90초 동안 공격력 +10"}, {"slot": "Passive", "name": "흑영", "explain": "적 플레이어 처치 시 그림자를 취합하고 대부분 스킬 쿨타임 초기화"}]},
};

export function getCypherProfile(characterName?: string | null): CypherProfile | null {
  if (!characterName) return null;
  return PROFILES[characterName] ?? null;
}
